services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel-network
        ports:
            - "8020:9000"
        environment:
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - LOG_CHANNEL=${LOG_CHANNEL}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=mysql
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - BROADCAST_DRIVER=${BROADCAST_DRIVER}
            - CACHE_DRIVER=${CACHE_DRIVER}
            - FILESYSTEM_DISK=${FILESYSTEM_DISK}
            - QUEUE_CONNECTION=${QUEUE_CONNECTION}
            - SESSION_DRIVER=${SESSION_DRIVER}
            - SESSION_LIFETIME=${SESSION_LIFETIME}
            - MEMCACHED_HOST=${MEMCACHED_HOST}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - MAIL_MAILER=${MAIL_MAILER}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
            - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
            - MAIL_FROM_NAME=${MAIL_FROM_NAME}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - AWS_BUCKET=${AWS_BUCKET}
            - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
            - PUSHER_APP_ID=${PUSHER_APP_ID}
            - PUSHER_APP_KEY=${PUSHER_APP_KEY}
            - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
            - PUSHER_HOST=${PUSHER_HOST}
            - PUSHER_PORT=${PUSHER_PORT}
            - PUSHER_SCHEME=${PUSHER_SCHEME}
            - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
            - CITY=${CITY}
            - WEATHER_API_KEY=${WEATHER_API_KEY}
            - X_TOKEN=${X_TOKEN}
        depends_on:
            - mysql
        command: sh -c "sleep 10 && php artisan migrate && php-fpm"

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: your_secure_password
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel-network

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - laravel-network

networks:
    laravel-network:

volumes:
    mysql_data:
